### ISSUE TITLE
Error upon installing

### ISSUE THREAD

**Issue by raiseerco** [daoleno/lenskit#2]
After running `yarn add @lenskit/react`, I've got:

```console
error An unexpected error occurred: "https://registry.yarnpkg.com/@lenskit%2freact: Not found".
```

**Comment by daoleno** [comment]
Thanks for trying it out. Fixed in [@lenskit/react@v0.0.1](https://github.com/daoleno/lenskit/releases/tag/%40lenskit%2Freact%40v0.0.1)
